name: AutoReplaceTool
version: '0.1.0'
main: io.github.woundedkoba.autoreplacetool.AutoReplaceTool
api-version: '26.3'
authors: [woundedkoba]
description: >
  This plugin automatically replaces a broken tool or weapon on the hotbar with another matching one from your inventory when it breaks.
website: buildlikestitch.online
